//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRC_UserApprove
    {
        public string id { get; set; }
        public string Email { get; set; }
        public string Permission { get; set; }
        public string FullName { get; set; }
        public string authority { get; set; }
    }
}
