//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Answer
    {
        public int AnswerID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public string Content { get; set; }
        public Nullable<int> State { get; set; }
    
        public virtual HR_Question HR_Question { get; set; }
    }
}
