//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_ABN_Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_ABN_Request()
        {
            this.HR_ABN_Items = new HashSet<HR_ABN_Items>();
        }
    
        public int ID { get; set; }
        public string RequestBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ApproveName { get; set; }
        public string ApproveMail { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string HrName { get; set; }
        public string HrMail { get; set; }
        public Nullable<int> Status { get; set; }
        public string ReasonReject { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_ABN_Items> HR_ABN_Items { get; set; }
        public virtual TBL_USERS_MST TBL_USERS_MST { get; set; }
    }
}
