//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_ABN_Mst
    {
        public int ID { get; set; }
        public string Division { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string Department { get; set; }
        public string Shift { get; set; }
        public string Line { get; set; }
        public string EmpID { get; set; }
        public string Name { get; set; }
        public string Operation { get; set; }
        public string ShiftStart { get; set; }
        public string ActualStart { get; set; }
        public string ShiftEnd { get; set; }
        public string ActualEnd { get; set; }
        public string Late { get; set; }
        public string Soon { get; set; }
        public string Abnormal { get; set; }
        public Nullable<System.DateTime> uploaddate { get; set; }
        public string MailAdmin { get; set; }
    }
}
