//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_CS_ShiftChange_Items
    {
        public string Employee_ID { get; set; }
        public int RequestID { get; set; }
        public string NewShift { get; set; }
        public string NAME { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string Detail { get; set; }
        public string OldShift { get; set; }
    
        public virtual HR_CS_ShiftChange_Request HR_CS_ShiftChange_Request { get; set; }
    }
}
