//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Employee_Course
    {
        public string Emp_ID { get; set; }
        public int Course_ID { get; set; }
        public Nullable<System.DateTime> Training_Date { get; set; }
        public string Trainner { get; set; }
        public string Title { get; set; }
    
        public virtual HR_Training_Emp HR_Training_Emp { get; set; }
        public virtual HR_Training_Plan HR_Training_Plan { get; set; }
    }
}
