//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Exam_Detail
    {
        public int ExamDetail_ID { get; set; }
        public int ExamID { get; set; }
        public int QuestionID { get; set; }
    
        public virtual HR_Exam HR_Exam { get; set; }
        public virtual HR_Question HR_Question { get; set; }
    }
}
