//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_Exam()
        {
            this.HR_Exam_Detail = new HashSet<HR_Exam_Detail>();
        }
    
        public int ExamID { get; set; }
        public string NameExam { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<double> Point { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> QuestionNumber { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string State { get; set; }
        public Nullable<int> UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Exam_Detail> HR_Exam_Detail { get; set; }
        public virtual HR_Training_Plan HR_Training_Plan { get; set; }
    }
}
