//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Meals_Order
    {
        public int ID { get; set; }
        public string EmpID { get; set; }
        public string FullName { get; set; }
        public string RequestEmail { get; set; }
        public string RequestDate { get; set; }
        public Nullable<int> Dept { get; set; }
        public Nullable<int> Shift { get; set; }
        public Nullable<int> QtyMeal { get; set; }
        public Nullable<int> QtyMilk { get; set; }
        public Nullable<int> QtyWater { get; set; }
        public string HRName { get; set; }
        public string HREmail { get; set; }
        public Nullable<int> HRApproved { get; set; }
        public string HRApprovedDate { get; set; }
        public string Comment { get; set; }
        public string MilkFilePath { get; set; }
        public string WaterFilePath { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual TBL_DEPARTMENT_MST TBL_DEPARTMENT_MST { get; set; }
        public virtual TBL_SHIFT_MST TBL_SHIFT_MST { get; set; }
    }
}
