//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Tran_Van_MST
    {
        public int ID { get; set; }
        public string NumberPlate { get; set; }
        public string DriverName { get; set; }
        public string DriverPhone { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
