//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_TRAINING_REG
    {
        public int id { get; set; }
        public string Strategic { get; set; }
        public string StrategicSuggestion { get; set; }
        public string Problems { get; set; }
        public string ProblemsSuggestion { get; set; }
        public string JobEvolution { get; set; }
        public string JobEvolutionSuggestion { get; set; }
        public string CulturalChanges { get; set; }
        public string CulturalChangesSuggestion { get; set; }
        public string StaffNeeds { get; set; }
        public string StaffNeedsSuggestion { get; set; }
        public string StaffNeedsKey { get; set; }
        public string StaffNeedsKeySuggestion { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string AssignTo { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual TBL_DEPARTMENT_MST TBL_DEPARTMENT_MST { get; set; }
    }
}
