//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Training_Plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_Training_Plan()
        {
            this.HR_Employee_Course = new HashSet<HR_Employee_Course>();
            this.HR_Exam = new HashSet<HR_Exam>();
        }
    
        public int id { get; set; }
        public string CourseName { get; set; }
        public string Trainer { get; set; }
        public string Internal { get; set; }
        public string External { get; set; }
        public string Category { get; set; }
        public string TargetAudience { get; set; }
        public string Direct { get; set; }
        public string Indirect { get; set; }
        public string OfficeStaff { get; set; }
        public string Supervisor { get; set; }
        public string Manager { get; set; }
        public Nullable<double> EstimatedPax { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<double> TotalHours { get; set; }
        public Nullable<double> Cost { get; set; }
        public string Explanation { get; set; }
        public string Jan { get; set; }
        public string Feb { get; set; }
        public string Mar { get; set; }
        public string Apr { get; set; }
        public string May { get; set; }
        public string Jun { get; set; }
        public string Jul { get; set; }
        public string Aug { get; set; }
        public string Sep { get; set; }
        public string Oct { get; set; }
        public string Nov { get; set; }
        public string Dec { get; set; }
        public Nullable<int> Year { get; set; }
        public string BigMenu { get; set; }
        public string SmallMenu { get; set; }
        public string Level1 { get; set; }
        public string Level2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Employee_Course> HR_Employee_Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Exam> HR_Exam { get; set; }
    }
}
