//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Training_Emp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_Training_Emp()
        {
            this.HR_Employee_Course = new HashSet<HR_Employee_Course>();
        }
    
        public string Emp_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> DEPARTMENT { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Employee_Course> HR_Employee_Course { get; set; }
        public virtual TBL_DEPARTMENT_MST TBL_DEPARTMENT_MST { get; set; }
    }
}
