//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPI_Setting
    {
        public int ID { get; set; }
        public string KPIYear { get; set; }
        public string DeptName { get; set; }
        public string EmpID { get; set; }
        public string Position { get; set; }
        public string SupervisorID { get; set; }
        public string ManagerID { get; set; }
        public string KPIitems { get; set; }
        public string Q1 { get; set; }
        public string Q2 { get; set; }
        public string Q3 { get; set; }
        public string Q4 { get; set; }
        public Nullable<int> EmpSubmitted { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public Nullable<int> EvaluatorReviewed { get; set; }
        public Nullable<System.DateTime> ReviewedDate { get; set; }
        public Nullable<int> ManagerApproved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> Period { get; set; }
        public string KPIweight { get; set; }
        public string Note { get; set; }
        public string CoreValues { get; set; }
        public string CmtEmp { get; set; }
        public string CmtManager { get; set; }
        public string Level { get; set; }
    }
}
