//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPI_Emp_List
    {
        public int ID { get; set; }
        public string Position { get; set; }
        public string EmpID { get; set; }
        public string EmpName { get; set; }
        public string SupEmail { get; set; }
        public string MgrEmail { get; set; }
        public string EmpEmail { get; set; }
        public string DeptName { get; set; }
    }
}
