//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUV_BOM
    {
        public int ID { get; set; }
        public string CompWO { get; set; }
        public string AsstWO { get; set; }
        public string MnfStyle { get; set; }
        public string SelStyle { get; set; }
        public string PkgStyle { get; set; }
        public string Color { get; set; }
        public string WC { get; set; }
        public string Size { get; set; }
        public Nullable<int> Week { get; set; }
        public string Item { get; set; }
        public Nullable<double> Quantity { get; set; }
    
        public virtual MUV_ITEMS MUV_ITEMS { get; set; }
    }
}
