//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUV_CT_BOM
    {
        public string MFG_PATH_ID { get; set; }
        public string STYLE_CD { get; set; }
        public string COLOR_CD { get; set; }
        public string SIZE_CD { get; set; }
        public string COMP_STYLE_CD { get; set; }
        public string COM_SIZE_CD { get; set; }
        public string COMP_ATTRIBUTE_CD { get; set; }
        public string UNIT_OF_MEASURE { get; set; }
        public string REQD_QTY { get; set; }
        public string TOTAL_COST_AMT { get; set; }
        public string CURR_YIELD_LOSS_PCT { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public int ID { get; set; }
    }
}
