//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUV_Actual
    {
        public int ID { get; set; }
        public string Item { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string AsstWL { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<int> Week { get; set; }
        public string GroupName { get; set; }
    
        public virtual MUV_ITEMS MUV_ITEMS { get; set; }
    }
}
