//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUV_CT_Goal
    {
        public string Plant { get; set; }
        public string Month { get; set; }
        public string WK { get; set; }
        public Nullable<double> OPC { get; set; }
        public Nullable<double> Stretch { get; set; }
        public int Id { get; set; }
    }
}
