//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUV_CT_ACI
    {
        public string ACTIVITY_DATE { get; set; }
        public string YEAR { get; set; }
        public string PLANT { get; set; }
        public string LW_ACCT_UNIT { get; set; }
        public string LW_ACCOUNT { get; set; }
        public string LW_SUB_ACCOUNT { get; set; }
        public string STYLE { get; set; }
        public string COLOR { get; set; }
        public string ATTRIBUTE_CD { get; set; }
        public string SIZE_CD { get; set; }
        public string STYLE_DESC { get; set; }
        public string INVENTORY_TRANS_QTY { get; set; }
        public string INVENTORY_TRANS_AMT { get; set; }
        public string DEBIT_CREDIT_CD { get; set; }
        public string GENERIC_ORDER_NO { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public int ID { get; set; }
    }
}
