//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUV_CT_SellingWC
    {
        public int Id { get; set; }
        public string MFG { get; set; }
        public string Group { get; set; }
        public string UserUpdate { get; set; }
        public string UploadDate { get; set; }
    }
}
