//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OL_OT_Record_W
    {
        public int id { get; set; }
        public string EmpID { get; set; }
        public double C1 { get; set; }
        public double C2 { get; set; }
        public double C3 { get; set; }
        public double C4 { get; set; }
        public double C5 { get; set; }
        public double C6 { get; set; }
        public double C7 { get; set; }
        public double C8 { get; set; }
        public double C9 { get; set; }
        public double C10 { get; set; }
        public double C11 { get; set; }
        public double C12 { get; set; }
        public double C13 { get; set; }
        public double C14 { get; set; }
        public double C15 { get; set; }
        public double C16 { get; set; }
        public double C17 { get; set; }
        public double C18 { get; set; }
        public double C19 { get; set; }
        public double C20 { get; set; }
        public double C21 { get; set; }
        public double C22 { get; set; }
        public double C23 { get; set; }
        public double C24 { get; set; }
        public double C25 { get; set; }
        public double C26 { get; set; }
        public double C27 { get; set; }
        public double C28 { get; set; }
        public double C29 { get; set; }
        public double C30 { get; set; }
        public double C31 { get; set; }
        public double C32 { get; set; }
        public double C33 { get; set; }
        public double C34 { get; set; }
        public double C35 { get; set; }
        public double C36 { get; set; }
        public double C37 { get; set; }
        public double C38 { get; set; }
        public double C39 { get; set; }
        public double C40 { get; set; }
        public double C41 { get; set; }
        public double C42 { get; set; }
        public double C43 { get; set; }
        public double C44 { get; set; }
        public double C45 { get; set; }
        public double C46 { get; set; }
        public double C47 { get; set; }
        public double C48 { get; set; }
        public double C49 { get; set; }
        public double C50 { get; set; }
        public double C51 { get; set; }
        public double C52 { get; set; }
        public double C53 { get; set; }
    
        public virtual OL_User_Approver OL_User_Approver { get; set; }
    }
}
