//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OL_OT_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OL_OT_Details()
        {
            this.OL_OT_Item = new HashSet<OL_OT_Item>();
        }
    
        public int OT_ID { get; set; }
        public string Section { get; set; }
        public Nullable<int> Dept { get; set; }
        public Nullable<System.DateTime> EmpSubmit { get; set; }
        public string ApproverName { get; set; }
        public string ApproverEmail { get; set; }
        public Nullable<System.DateTime> AppSubmitted { get; set; }
        public Nullable<System.DateTime> AppApproval { get; set; }
        public Nullable<int> AppStatus { get; set; }
        public string HRName { get; set; }
        public string HREmail { get; set; }
        public Nullable<System.DateTime> HRSubmit { get; set; }
        public Nullable<System.DateTime> HRApproval { get; set; }
        public Nullable<int> HRStatus { get; set; }
        public string ReqNo { get; set; }
        public string Notes { get; set; }
        public string ReqName { get; set; }
        public string ReqEmail { get; set; }
        public string Comments { get; set; }
        public string Mon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OL_OT_Item> OL_OT_Item { get; set; }
        public virtual TBL_USERS_MST TBL_USERS_MST { get; set; }
    }
}
