//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OL_User_Approver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OL_User_Approver()
        {
            this.OL_OT_Record_M = new HashSet<OL_OT_Record_M>();
            this.OL_OT_Record_W = new HashSet<OL_OT_Record_W>();
            this.OL_Leave_Item = new HashSet<OL_Leave_Item>();
            this.OL_OT_Item = new HashSet<OL_OT_Item>();
        }
    
        public string EmpID { get; set; }
        public string UserCD { get; set; }
        public string EmpName { get; set; }
        public string EmpEmail { get; set; }
        public Nullable<int> Section { get; set; }
        public string Dept { get; set; }
        public string ApproverName { get; set; }
        public string ApproverEmail { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public string Line { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OL_OT_Record_M> OL_OT_Record_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OL_OT_Record_W> OL_OT_Record_W { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OL_Leave_Item> OL_Leave_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OL_OT_Item> OL_OT_Item { get; set; }
    }
}
