//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_TeaBreak_Mst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PR_TeaBreak_Mst()
        {
            this.PR_TeaBreak_Items = new HashSet<PR_TeaBreak_Items>();
        }
    
        public int ID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string Name_teabreak { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual PR_TeaBreak_Group PR_TeaBreak_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PR_TeaBreak_Items> PR_TeaBreak_Items { get; set; }
    }
}
