//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_TeaBreak_Items
    {
        public int TeaBreakID { get; set; }
        public int RequestID { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual PR_TeaBreak_Mst PR_TeaBreak_Mst { get; set; }
        public virtual PR_TeaBreak_Request PR_TeaBreak_Request { get; set; }
    }
}
