//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STA_Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STA_Orders()
        {
            this.STA_Order_Item = new HashSet<STA_Order_Item>();
        }
    
        public int OrderId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> DepId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string FeedBack { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateTimeApprove { get; set; }
        public string Requester { get; set; }
        public string Approver { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STA_Order_Item> STA_Order_Item { get; set; }
        public virtual TBL_USERS_MST TBL_USERS_MST { get; set; }
        public virtual TBL_USERS_MST TBL_USERS_MST1 { get; set; }
    }
}
