//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STA_AllowDate
    {
        public int id { get; set; }
        public Nullable<int> BeginDate { get; set; }
        public Nullable<int> EndDate { get; set; }
    }
}
