//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STA_Dep_Budget
    {
        public int ID { get; set; }
        public int DepId { get; set; }
        public decimal Budget { get; set; }
        public Nullable<decimal> BudgetBonus { get; set; }
        public string Name { get; set; }
        public string Approver { get; set; }
        public string Division { get; set; }
    }
}
