//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CT_SAH
    {
        public string GARMENT_STYLE { get; set; }
        public string MFG_STYLE { get; set; }
        public Nullable<float> CTEX { get; set; }
        public Nullable<float> SPRD_BK_FT { get; set; }
        public Nullable<float> SPRD_LINER { get; set; }
        public Nullable<float> CUT_BK_FT { get; set; }
        public Nullable<float> CUT_LINER { get; set; }
        public Nullable<float> TOTAL_SPRD { get; set; }
        public Nullable<float> TOTAL_CUT { get; set; }
        public Nullable<float> LEG_BINDING { get; set; }
        public Nullable<float> WASTE_BINDING { get; set; }
        public Nullable<float> TUBING { get; set; }
        public Nullable<float> LOTTING { get; set; }
        public Nullable<float> SEAM_JONT { get; set; }
        public Nullable<float> TOTAL { get; set; }
        public Nullable<System.DateTime> TS_1 { get; set; }
        public string TS_1_USER { get; set; }
    }
}
