//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LTS_NONREC_LOT
    {
        public int id { get; set; }
        public string Asst_WL { get; set; }
        public string Asst_SKU { get; set; }
        public string Selling_Style { get; set; }
        public string Comp_WL { get; set; }
        public string Size { get; set; }
        public string Loc_Name { get; set; }
        public Nullable<double> Rec_Qty { get; set; }
        public string Aging { get; set; }
        public Nullable<System.DateTime> Issued_date { get; set; }
    }
}
