//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USERS_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_USERS_MST()
        {
            this.OL_LeaveDetails = new HashSet<OL_LeaveDetails>();
            this.OL_OT_Details = new HashSet<OL_OT_Details>();
            this.STA_Orders = new HashSet<STA_Orders>();
            this.STA_Orders1 = new HashSet<STA_Orders>();
            this.TBL_PERMISSION = new HashSet<TBL_PERMISSION>();
            this.WH_Supply_Request = new HashSet<WH_Supply_Request>();
            this.HR_ABN_Request = new HashSet<HR_ABN_Request>();
            this.TD_TimeDeduction_Request = new HashSet<TD_TimeDeduction_Request>();
            this.HR_CS_ShiftChange_Request = new HashSet<HR_CS_ShiftChange_Request>();
            this.TDS_SupportTimeRequest = new HashSet<TDS_SupportTimeRequest>();
            this.GRC_TransferAssets = new HashSet<GRC_TransferAssets>();
            this.TBL_RC_Request = new HashSet<TBL_RC_Request>();
            this.TBL_RC_Request_Data = new HashSet<TBL_RC_Request_Data>();
            this.TBL_KANBAN = new HashSet<TBL_KANBAN>();
            this.TBL_KANBAN1 = new HashSet<TBL_KANBAN>();
            this.TBL_KANBAN2 = new HashSet<TBL_KANBAN>();
            this.TBL_KANBAN3 = new HashSet<TBL_KANBAN>();
            this.TBL_KANBAN4 = new HashSet<TBL_KANBAN>();
            this.TBL_KANBAN_DATA = new HashSet<TBL_KANBAN_DATA>();
            this.TBL_KANBAN_DATA1 = new HashSet<TBL_KANBAN_DATA>();
            this.TBL_KANBAN_DATA2 = new HashSet<TBL_KANBAN_DATA>();
            this.TBL_KANBAN_DATA3 = new HashSet<TBL_KANBAN_DATA>();
            this.TBL_KANBAN_DATA4 = new HashSet<TBL_KANBAN_DATA>();
            this.TBL_LTS_Details = new HashSet<TBL_LTS_Details>();
        }
    
        public string USERNAME { get; set; }
        public string FULLNAME { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> WSHOP_ID { get; set; }
        public Nullable<int> ACTIVATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> TS_1 { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
        public string Password { get; set; }
        public Nullable<int> DEPT { get; set; }
        public Nullable<int> POSID { get; set; }
        public string ResetSession { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OL_LeaveDetails> OL_LeaveDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OL_OT_Details> OL_OT_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STA_Orders> STA_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STA_Orders> STA_Orders1 { get; set; }
        public virtual TBL_DEPARTMENT_MST TBL_DEPARTMENT_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PERMISSION> TBL_PERMISSION { get; set; }
        public virtual TBL_Positions_MST TBL_Positions_MST { get; set; }
        public virtual TBL_WSHOP_MST TBL_WSHOP_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WH_Supply_Request> WH_Supply_Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_ABN_Request> HR_ABN_Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_TimeDeduction_Request> TD_TimeDeduction_Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_CS_ShiftChange_Request> HR_CS_ShiftChange_Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDS_SupportTimeRequest> TDS_SupportTimeRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRC_TransferAssets> GRC_TransferAssets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_RC_Request> TBL_RC_Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_RC_Request_Data> TBL_RC_Request_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_KANBAN> TBL_KANBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_KANBAN> TBL_KANBAN1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_KANBAN> TBL_KANBAN2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_KANBAN> TBL_KANBAN3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_KANBAN> TBL_KANBAN4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_KANBAN_DATA> TBL_KANBAN_DATA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_KANBAN_DATA> TBL_KANBAN_DATA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_KANBAN_DATA> TBL_KANBAN_DATA2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_KANBAN_DATA> TBL_KANBAN_DATA3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_KANBAN_DATA> TBL_KANBAN_DATA4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_LTS_Details> TBL_LTS_Details { get; set; }
    }
}
