//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_WLOT_LOC
    {
        public int ID { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public Nullable<System.DateTime> ISSUE_DATE { get; set; }
        public string WK { get; set; }
        public Nullable<double> HOURS { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<int> SHIFT { get; set; }
        public string LINE { get; set; }
        public Nullable<System.DateTime> TS_1 { get; set; }
        public string TS_1_USER { get; set; }
    
        public virtual TBL_GROUP_MST TBL_GROUP_MST { get; set; }
    }
}
