//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LTS_APPROVE
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Mail { get; set; }
        public Nullable<int> Manager { get; set; }
        public string MemberOf { get; set; }
    }
}
