//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CT_QC_COMPNT_DEFECT
    {
        public int ID { get; set; }
        public int ORDER_TBL_ID { get; set; }
        public Nullable<int> COMPNT_ID { get; set; }
        public Nullable<int> F { get; set; }
        public Nullable<int> M { get; set; }
        public Nullable<int> L { get; set; }
        public Nullable<System.DateTime> TS_1 { get; set; }
        public string TS_1_USER { get; set; }
        public Nullable<int> F_QTY { get; set; }
        public Nullable<int> M_QTY { get; set; }
        public Nullable<int> L_QTY { get; set; }
        public string MARKER { get; set; }
    }
}
