//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RC_Request_Data_Detail
    {
        public Nullable<int> ID { get; set; }
        public int RcID { get; set; }
        public string MaterialCode { get; set; }
        public Nullable<int> SewingError { get; set; }
        public Nullable<int> CuttingError { get; set; }
        public Nullable<int> SewingLack { get; set; }
        public Nullable<int> CuttingLack { get; set; }
        public Nullable<int> FabricError { get; set; }
        public Nullable<int> SewingTest { get; set; }
        public string LeaderName { get; set; }
        public string AltMaterialCode { get; set; }
        public string WORecut { get; set; }
        public Nullable<int> CcdQty { get; set; }
        public Nullable<int> WHQty { get; set; }
        public Nullable<int> CcdConfirm { get; set; }
    
        public virtual TBL_RC_Request_Data TBL_RC_Request_Data { get; set; }
    }
}
