//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PPack_Data
    {
        public string WLOT { get; set; }
        public string Label_ID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<int> Plant_Code { get; set; }
        public int ID { get; set; }
    }
}
