//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LTS_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_LTS_Details()
        {
            this.TBL_LTS_Items = new HashSet<TBL_LTS_Items>();
        }
    
        public int ID { get; set; }
        public string Asst_WL { get; set; }
        public Nullable<double> Rec_Qty { get; set; }
        public Nullable<double> FQ_Qty { get; set; }
        public string Group_Name { get; set; }
        public Nullable<int> Prod_PIC { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> Submitted_date { get; set; }
        public string Prod_Status { get; set; }
        public string Prod_mail { get; set; }
        public Nullable<System.DateTime> Prod_Date { get; set; }
        public Nullable<int> PM_PIC { get; set; }
        public string PM_Status { get; set; }
        public Nullable<System.DateTime> PM_Date { get; set; }
        public string PM_mail { get; set; }
        public Nullable<int> Odd_PIC { get; set; }
        public string Odd_Status { get; set; }
        public string Odd_mail { get; set; }
        public Nullable<System.DateTime> Odd_Date { get; set; }
        public Nullable<int> IA_PIC { get; set; }
        public string IA_Status { get; set; }
        public string IA_mail { get; set; }
        public Nullable<System.DateTime> IA_Date { get; set; }
        public Nullable<int> status { get; set; }
        public string ReasonReject { get; set; }
    
        public virtual TBL_USERS_MST TBL_USERS_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_LTS_Items> TBL_LTS_Items { get; set; }
    }
}
