//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_GROUP_SHIFT
    {
        public int ID { get; set; }
        public int GROUP_TYPE { get; set; }
        public int SHIFT_ID { get; set; }
        public System.DateTime MONTH_EFF { get; set; }
    }
}
