//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RAW_DATA
    {
        public string WLOT { get; set; }
        public string LABEL_ID { get; set; }
        public string LABEL_TYPE { get; set; }
        public string PkgStyle { get; set; }
        public string COLOR { get; set; }
        public string SIZE { get; set; }
        public Nullable<System.DateTime> TS_1 { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public int ID { get; set; }
        public Nullable<int> Plant_Code { get; set; }
        public string TS_1_USER { get; set; }
        public string MnfStyle { get; set; }
        public string SellingStyle { get; set; }
        public string GROUP_NAME { get; set; }
    }
}
