//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RC_Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_RC_Request()
        {
            this.TBL_RC_Request_Detail = new HashSet<TBL_RC_Request_Detail>();
        }
    
        public int ID { get; set; }
        public string WO { get; set; }
        public string SellingStyle { get; set; }
        public string Size { get; set; }
        public string MnfColor { get; set; }
        public string MnfStyle { get; set; }
        public string RequestDate { get; set; }
        public string RequestBy { get; set; }
        public string QCSewBy { get; set; }
        public Nullable<int> QCSewStatus { get; set; }
        public string QCSewDate { get; set; }
        public string RequestManager { get; set; }
        public Nullable<int> RequestManagerStatus { get; set; }
        public string ManagerDate { get; set; }
        public string PlanBy { get; set; }
        public Nullable<int> PlanStatus { get; set; }
        public string PlanDate { get; set; }
        public string CCDRequestBy { get; set; }
        public Nullable<int> CCDRequesStatus { get; set; }
        public string CCDRequesDate { get; set; }
        public string WHBy { get; set; }
        public Nullable<int> WHStatus { get; set; }
        public string WHDate { get; set; }
        public string CCDABy { get; set; }
        public Nullable<int> CCDApproveStatus { get; set; }
        public string CCDApproveDate { get; set; }
        public string QCCutBy { get; set; }
        public Nullable<int> QCCutStatus { get; set; }
        public string QCCutDate { get; set; }
        public Nullable<int> ProductStatus { get; set; }
        public string ProductDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_RC_Request_Detail> TBL_RC_Request_Detail { get; set; }
        public virtual TBL_USERS_MST TBL_USERS_MST { get; set; }
    }
}
