//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TTS_ORDER_ST_LOG
    {
        public System.DateTime DateDelete { get; set; }
        public string WO { get; set; }
        public string ASST { get; set; }
        public string STATUS { get; set; }
        public string MfgStyle { get; set; }
        public string SellingStyle { get; set; }
    }
}
