//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LINE_MST
    {
        public int LINE_ID { get; set; }
        public int GROUP_ID { get; set; }
        public Nullable<System.DateTime> TS { get; set; }
        public Nullable<System.DateTime> TS_USER { get; set; }
        public Nullable<int> ACTIVATE { get; set; }
    }
}
