//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PERMISSION
    {
        public string USERNAME { get; set; }
        public int MO_ID { get; set; }
        public Nullable<System.DateTime> TS_1 { get; set; }
        public string TS_1_USER { get; set; }
    
        public virtual TBL_CATEGORIES TBL_CATEGORIES { get; set; }
        public virtual TBL_USERS_MST TBL_USERS_MST { get; set; }
    }
}
