//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CT_TICKET_ORDER_FABRIC_DETAIL
    {
        public int ID_TICKET_DETAIL { get; set; }
        public Nullable<int> ID_TICKET { get; set; }
        public Nullable<int> ORDER_IN_LIST { get; set; }
        public string CODE_FABRIC { get; set; }
        public string NOTE_DETAIL { get; set; }
        public Nullable<double> NUMBER_REQUEST { get; set; }
        public string WO { get; set; }
        public string ASSORTMENT { get; set; }
        public string NOTE_TTS { get; set; }
    }
}
