//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PROD_PLAN
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> PLAN_DATE { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public string STYLE { get; set; }
        public Nullable<double> LABOR { get; set; }
        public Nullable<double> SAH { get; set; }
        public Nullable<double> TARGET_QTY { get; set; }
        public Nullable<System.DateTime> TS_1 { get; set; }
        public Nullable<System.DateTime> TS_2 { get; set; }
        public string TS_1_USER { get; set; }
        public string TS_2_USER { get; set; }
        public Nullable<int> LINE_ID { get; set; }
    }
}
