//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_WORK_LOT
    {
        public string WLOT_ID { get; set; }
        public Nullable<double> TOTAL_DZ { get; set; }
        public Nullable<double> ACTUAL_DZ { get; set; }
        public Nullable<System.DateTime> TS_1 { get; set; }
        public Nullable<System.DateTime> TS_2 { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
