//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_QC_BUSINESS_TARGET
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public Nullable<double> TARGET { get; set; }
        public Nullable<System.DateTime> TS_2 { get; set; }
        public string TS_2_USER { get; set; }
        public Nullable<int> BIZ_ID { get; set; }
        public Nullable<int> TARGET_2 { get; set; }
    }
}
