//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RC_ComParts
    {
        public string MnfStyle { get; set; }
        public string FabricCD { get; set; }
        public string SPCode { get; set; }
        public string PartsDesc { get; set; }
        public int id { get; set; }
    }
}
