//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OUTPUT_UPDATE
    {
        public int ID { get; set; }
        public int FRAME_ID { get; set; }
        public string GROUP_NAME { get; set; }
        public string PLANT_NAME { get; set; }
        public string WS_NAME { get; set; }
        public string SHIFT_NAME { get; set; }
        public Nullable<double> TARGET { get; set; }
        public Nullable<double> ACTUAL { get; set; }
        public Nullable<double> EFFICIENCY { get; set; }
        public Nullable<int> WL_OVER_7DAYS { get; set; }
        public Nullable<System.DateTime> TS_1 { get; set; }
        public Nullable<double> PIECE { get; set; }
        public string COLOR { get; set; }
    }
}
