//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CATEGORIES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CATEGORIES()
        {
            this.TBL_PERMISSION = new HashSet<TBL_PERMISSION>();
        }
    
        public int CA_ID { get; set; }
        public string CA_NAME { get; set; }
        public string CA_URL { get; set; }
        public Nullable<int> CA_PARENT { get; set; }
        public Nullable<bool> CA_SPLIT { get; set; }
        public Nullable<bool> CA_STATUS { get; set; }
        public Nullable<int> MenuShow { get; set; }
        public string AccessDefault { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PERMISSION> TBL_PERMISSION { get; set; }
    }
}
