//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SAH_MST
    {
        public string Sel_Style { get; set; }
        public double SAH { get; set; }
        public Nullable<System.DateTime> TS { get; set; }
        public string TS_USER { get; set; }
        public string SizeCD { get; set; }
        public string Color { get; set; }
        public string Pkg_Style { get; set; }
        public string Size_Des { get; set; }
        public string Status { get; set; }
        public string MnfStyle { get; set; }
    }
}
