//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_QC_PROCESS_MST
    {
        public int PROCESS_ID { get; set; }
        public Nullable<int> PROCESS_CAT_ID { get; set; }
        public string NAME { get; set; }
        public string NAME_VNM { get; set; }
    }
}
