//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_QC_ENDLINE_WL_SAMPLE
    {
        public int ID { get; set; }
        public string BIZI_ID { get; set; }
        public Nullable<int> TOTAL_SAMPLE { get; set; }
        public string TS_1_USER { get; set; }
        public Nullable<System.DateTime> TS_1 { get; set; }
        public string LINE_ID { get; set; }
    }
}
