//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_WL
    {
        public string WL_ID { get; set; }
        public string ASST_WL_ID { get; set; }
        public string STYLE { get; set; }
        public string COLOR { get; set; }
        public string SIZE { get; set; }
        public string LOCATION { get; set; }
        public Nullable<System.DateTime> RECIEVE_DATE { get; set; }
        public Nullable<System.DateTime> ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> TS_1 { get; set; }
        public string TS_1_USER { get; set; }
        public Nullable<double> QUANTITY { get; set; }
    }
}
