//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_GROUP_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_GROUP_MST()
        {
            this.TBL_CASE_LABEL = new HashSet<TBL_CASE_LABEL>();
            this.TBL_Eff_Target = new HashSet<TBL_Eff_Target>();
            this.TBL_KANBAN_DATA = new HashSet<TBL_KANBAN_DATA>();
            this.TBL_KANBAN = new HashSet<TBL_KANBAN>();
            this.TBL_WLOT_LOC = new HashSet<TBL_WLOT_LOC>();
            this.Tbl_Working_Hour = new HashSet<Tbl_Working_Hour>();
            this.WH_Supply_Request = new HashSet<WH_Supply_Request>();
        }
    
        public int GROUP_ID { get; set; }
        public string GROUP_NAME { get; set; }
        public string UPDATE_BY { get; set; }
        public int WSHOP_ID { get; set; }
        public Nullable<int> Activate { get; set; }
    
        public virtual TBL_BUSINESS_MST TBL_BUSINESS_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CASE_LABEL> TBL_CASE_LABEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Eff_Target> TBL_Eff_Target { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_KANBAN_DATA> TBL_KANBAN_DATA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_KANBAN> TBL_KANBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_WLOT_LOC> TBL_WLOT_LOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Working_Hour> Tbl_Working_Hour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WH_Supply_Request> WH_Supply_Request { get; set; }
    }
}
