//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ASST_WL
    {
        public string ASST_ID { get; set; }
        public string STYLE { get; set; }
        public string COLOR { get; set; }
        public string SIZE { get; set; }
        public string ASN { get; set; }
        public Nullable<int> PLANT { get; set; }
        public Nullable<System.DateTime> TS_1 { get; set; }
    }
}
