//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_QC_AQL
    {
        public int ID { get; set; }
        public int RANGE_FROM { get; set; }
        public int RANGE_TO { get; set; }
        public Nullable<int> SAMPLE_QTY { get; set; }
        public Nullable<int> MAX_DEF { get; set; }
    }
}
