//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_TimeDeduction_Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TD_TimeDeduction_Request()
        {
            this.TD_TimeDeduction_Items = new HashSet<TD_TimeDeduction_Items>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string RequestBy { get; set; }
        public string LMs { get; set; }
        public string LMsMail { get; set; }
        public Nullable<System.DateTime> LMsDate { get; set; }
        public string HRProcess { get; set; }
        public string HRProcessMail { get; set; }
        public Nullable<System.DateTime> HRProcessDate { get; set; }
        public string HRCBSup { get; set; }
        public string HRCBSupMail { get; set; }
        public Nullable<System.DateTime> HRCBSupDate { get; set; }
        public double Status { get; set; }
        public string ReasonReject { get; set; }
        public Nullable<int> StatusSupport { get; set; }
    
        public virtual TBL_USERS_MST TBL_USERS_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_TimeDeduction_Items> TD_TimeDeduction_Items { get; set; }
    }
}
