//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_TimeDeduction_Items
    {
        public int ID { get; set; }
        public int RequestID { get; set; }
        public string Employee_ID { get; set; }
        public string NAME { get; set; }
        public string Line { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string Content { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> DeductOT { get; set; }
    
        public virtual TD_TimeDeduction_Request TD_TimeDeduction_Request { get; set; }
    }
}
