//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDS_SupportTimeItems
    {
        public int ID { get; set; }
        public int RequestID { get; set; }
        public string Employee_ID { get; set; }
        public string NAME { get; set; }
        public string Line { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Detail { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> DeductOT { get; set; }
        public Nullable<double> SupportHours { get; set; }
        public Nullable<double> SupportEff { get; set; }
        public Nullable<double> Payment { get; set; }
        public Nullable<int> DeductionID { get; set; }
    
        public virtual TDS_SupportTimeRequest TDS_SupportTimeRequest { get; set; }
    }
}
