//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WH_Item_location
    {
        public int ID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string LocationName { get; set; }
        public Nullable<double> QuantityOut { get; set; }
    
        public virtual WH_Supply_Request_Item WH_Supply_Request_Item { get; set; }
    }
}
