//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WH_Supply_Request_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WH_Supply_Request_Item()
        {
            this.WH_Item_location = new HashSet<WH_Item_location>();
        }
    
        public int ID { get; set; }
        public int RequestID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Note { get; set; }
        public string Unit { get; set; }
        public string SupplyName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WH_Item_location> WH_Item_location { get; set; }
        public virtual WH_Supply_Request WH_Supply_Request { get; set; }
    }
}
