//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WH_User_Approver
    {
        public string id { get; set; }
        public string value { get; set; }
        public string value2 { get; set; }
        public string value3 { get; set; }
        public string fullname { get; set; }
        public int tblID { get; set; }
    }
}
